### ISSUE TITLE
2020 and 2000 SF1 Support

### ISSUE THREAD

**Issue by PFurst2000** [vengroff/censusdis#111]
Does this package support the 2020 and 2000 SF1?
Thanks

**Comment by vengroff** [comment]
It works for 2000 and 2010. I do not think the census bureau has published 2020 via their API yet, but it should work as soon as they do. 

Here is an example for 2000 that I just tried.

```
import censusdis.data as ced

df_sf1 = ced.download(
    dataset='dec/sf1',
    vintage=2000,
    
    download_variables=['NAME', 'PCT012002', 'PCT012106'],
    
    state="*"
)

print(df_sf1.head())
```

This produces 

```
  STATE        NAME  PCT012002  PCT012106
0    01     Alabama    2146504    2300596
1    02      Alaska     324112     302820
2    04     Arizona    2561057    2569575
3    05    Arkansas    1304693    1368707
4    06  California   16874892   16996756
```

I'll add a demo notebook with a little more shortly.

**Comment by PFurst2000** [comment]
Thank you Darren! I think you are right about 2020 data not being on the
API yet. Great work!

**Comment by vengroff** [comment]
Thanks for asking, @PFurst2000. I'm glad we were able to give you what you were looking for.

One of the [design goals](https://github.com/vengroff/censusdis/blob/main/design-goals.md) of `censusdis` is that it should be able to handle any and all data sets the U.S. Census Bureau publishes via their API, and that as they publish new ones it should be able to download them without needing to be updated. There is a fair amount of code to query and manage metadata from the census API to ensure that this can happen.

If you'd like to see more about how you can discover and work with datasets, groups, and variables, check out the [Querying Available Data Sets.ipynb](https://github.com/vengroff/censusdis/blob/main/notebooks/Querying%20Available%20Data%20Sets.ipynb) sample notebook.

I also just added a demo notebook called [SF1.ipynb](https://github.com/vengroff/censusdis/blob/main/notebooks/datasets/SF1.ipynb) in the `datasets` subdirectory that specifically exercises SF1. It will be run automatically as part of the regular testing actions in our continuous integration so we can be sure it continues to work.

**Comment by vengroff** [comment]
For the second question, you are right, you have to merge. Here's how to do it. First, get the data:

```
df_state = ced.download(
    dataset='dec/sf1',
    vintage=2000,
    
    download_variables=['NAME'],
    group=['H010', 'P011'],
    state="*"
)

df_county = ced.download(
    dataset='dec/sf1',
    vintage=2000,
    
    download_variables=['NAME'],
    group=['H010', 'P011'],
    state="*",
    county="*"
)
```

Note that for brevity I chose some small groups.

Now we can merge as follows:

```
df = df_state.merge(
    df_county,
    on=['STATE'],
    suffixes=('_STATE', '_COUNTY')
)

print(df.head())
```

That produces:

```
  STATE NAME_STATE  H010001_STATE  P011001_STATE COUNTY              NAME_COUNTY  H010001_COUNTY  P011001_COUNTY
0    01    Alabama        4332380          75830    001  Autauga County, Alabama           43411             610
1    01    Alabama        4332380          75830    003  Baldwin County, Alabama          138141            2466
2    01    Alabama        4332380          75830    005  Barbour County, Alabama           26320             478
3    01    Alabama        4332380          75830    007     Bibb County, Alabama           19587             210
4    01    Alabama        4332380          75830    009   Blount County, Alabama           50414            2718
```

Of course, since there are many counties for each state, we end up with a denormalized result where each variable at the state level appears on many rows, one for each county, alongside the county level numbers. But I assume that is what you want so as to be able to do things like compare counties to the states that they are part of in your further analysis.

**Comment by vengroff** [comment]
And we're glad you are finding the package useful! Further questions, comments and suggestions are aways welcome.

**Comment by PFurst2000** [comment]
Thanks, this is really helpful! I have been a longtime user of Julien Leider's now discontinued censusdata package and was really happy to see you that you offer a new tool. I think my last question relates to the tree and leaves data. I am trying to collect the census variable information beyond the group and variable names. Specifically, Label (ie Estimate!!Total:!!Not Hispanic or Latino:!!White alone) and Concept (ie HISPANIC OR LATINO ORIGIN BY RACE). 

Is it possible to pull the Label and Concept data from the tree and leaves functions? I would like to join this data to my data tables so that I can clearly differentiate between multiple variable groups in the same dataframe. 

tree = ced.variables.group_tree(DATASET, YEAR, GROUP)
leaves = ced.variables.group_leaves(DATASET, YEAR, GROUP)

Is it correct that this software package supports Pandas? I seem to get errors when I try to use pandas dataframes with this package although that might be due to problems with my code itself.

**Comment by vengroff** [comment]
Hi @PFurst2000,

Thanks for giving `censusdis` a try. You can get more metadata on groups and variable using the `ced.variables.all_groups` and `ced.variables.all_variables` methods, which it turns out return `pandas.DataFrame`s.

For example:

```
import censusdis.data as ced

DATASET = 'dec/sf1'
YEAR = 2000

df_groups = ced.variables.all_groups(DATASET, YEAR)

print(type(df_groups))
print()
print(df_groups.head())
```

will print

```

<class 'pandas.core.frame.DataFrame'>

   DATASET  YEAR GROUP           DESCRIPTION
0  dec/sf1  2000  H001     HOUSING UNITS [1]
1  dec/sf1  2000  H002   URBAN AND RURAL [6]
2  dec/sf1  2000  H003  OCCUPANCY STATUS [3]
3  dec/sf1  2000  H004            TENURE [3]
4  dec/sf1  2000  H005    VACANCY STATUS [7]
```

What I normally do to find groups I am interested in is try to search for relevant strings in the descriptions, for example, I might look for the kind of data you are interested in with

```
print(df_groups[df_groups['DESCRIPTION'].str.contains('HISPANIC OR LATINO BY RACE')])
```

which produces

```
    DATASET  YEAR GROUP                                                                                       DESCRIPTION
59  dec/sf1  2000  P004                                       HISPANIC OR LATINO, AND NOT HISPANIC OR LATINO BY RACE [73]
61  dec/sf1  2000  P006  HISPANIC OR LATINO, AND NOT HISPANIC OR LATINO BY RACE FOR THE POPULATION 18 YEARS AND OVER [73]
63  dec/sf1  2000  P008                                                                   HISPANIC OR LATINO BY RACE [17]
65  dec/sf1  2000  P010                                             HISPANIC OR LATINO BY RACE (TOTAL RACES TALLIED) [15]
```

Note that everything I did with `df_groups` just now was a standard `pandas.DataFrame` operation.

Now let's say that based on this I want to look at group `P008`. I can do that with 

```
df_variables = ced.variables.all_variables('dec/sf1', 2000, 'P008')
print(df_variables)
```

will produces

```
<class 'pandas.core.frame.DataFrame'>

    YEAR  DATASET GROUP VARIABLE                                                                            LABEL  SUGGESTED_WEIGHT VALUES
0   2000  dec/sf1  P008  P008001                                                                            Total               NaN   None
1   2000  dec/sf1  P008  P008002                                                    Total!!Not Hispanic or Latino               NaN   None
2   2000  dec/sf1  P008  P008003                                       Total!!Not Hispanic or Latino!!White alone               NaN   None
3   2000  dec/sf1  P008  P008004                   Total!!Not Hispanic or Latino!!Black or African American alone               NaN   None
4   2000  dec/sf1  P008  P008005           Total!!Not Hispanic or Latino!!American Indian and Alaska Native alone               NaN   None
5   2000  dec/sf1  P008  P008006                                       Total!!Not Hispanic or Latino!!Asian alone               NaN   None
6   2000  dec/sf1  P008  P008007  Total!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone               NaN   None
7   2000  dec/sf1  P008  P008008                             Total!!Not Hispanic or Latino!!Some other race alone               NaN   None
8   2000  dec/sf1  P008  P008009                                 Total!!Not Hispanic or Latino!!Two or more races               NaN   None
9   2000  dec/sf1  P008  P008010                                                        Total!!Hispanic or Latino               NaN   None
10  2000  dec/sf1  P008  P008011                                           Total!!Hispanic or Latino!!White alone               NaN   None
11  2000  dec/sf1  P008  P008012                       Total!!Hispanic or Latino!!Black or African American alone               NaN   None
12  2000  dec/sf1  P008  P008013               Total!!Hispanic or Latino!!American Indian and Alaska Native alone               NaN   None
13  2000  dec/sf1  P008  P008014                                           Total!!Hispanic or Latino!!Asian alone               NaN   None
14  2000  dec/sf1  P008  P008015      Total!!Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone               NaN   None
15  2000  dec/sf1  P008  P008016                                 Total!!Hispanic or Latino!!Some other race alone               NaN   None
16  2000  dec/sf1  P008  P008017                                     Total!!Hispanic or Latino!!Two or more races               NaN   None
```

Again it is a `pandas.DataFrame` and from here I can do whatever I want with it.

Finally, all the data that the `ced.download` function returns is always in the form of a `pandas.DataFrame`. For example, the `merge` method I used to merge state and county data above is actually just the built in method `pandas.DataFrame.merge`.

**Comment by vengroff** [comment]
I'm going to close this issue now. Please, but all means. feel free to open another issue or start a discussion if you have additional questions.
