### ISSUE TITLE
Potential Bug with Remove_water

### ISSUE THREAD

**Issue by audreymarthin** [vengroff/censusdis#145]
When experimenting with different states' geographical maps with the remove_water=true flag setting, I found that certain land areas are cut off with the water. I believe these land areas are part of the census tracts and are not supposed to be cut off with the water. This issue persists with some but not all counties in these states. So far, I have tested with Maryland, Connecticut, Delaware, Hawaii, New Hampshire, and Massachusetts. However, I did not find this issue with the New York state. Could there be a possible bug within remove_water?

**Comment by CanyonFoot** [comment]
Can you post code with an example of one such area?

**Comment by vengroff** [comment]
@CanyonFoot maybe try the newly merged notebook https://github.com/vengroff/censusdis/blob/main/notebooks/Slow%20Water%20Removal%20Demo.ipynb. That's the one @audreymarthin was working on.

**Comment by audreymarthin** [comment]
@CanyonFoot yes, as Darren said you can see from the Slow Water Removal Demo notebook that certain counties in some states have a considerable size of land removed following the remove_water=True flag. I experimented with different states and different counties as well.

**Comment by CanyonFoot** [comment]
Gotcha - looking now!

**Comment by vengroff** [comment]
That might be just an off by one (order of magnitude) error.

**Comment by CanyonFoot** [comment]
That was my thought. Making that change would fix the issue in RI, and my guess is that 0..01 is conservative enough for the great majority of locations. I think the slivers function can also be used to improve the threshold use for removing the water - check out this example from Miami. All of those criss-crossing lines are real waterways (with total area exceeding the default threshold), but they produce a strange looking map. If we ran remove_slivers on the water polygons before doing the difference we could exclude them, hopefully with minimal risk of accidentally dropping anything we want.
![image](https://github.com/vengroff/censusdis/assets/33793596/951ee534-5f10-4009-9770-cab3092ef7db)

**Comment by vengroff** [comment]
I suspect there is no magic bullet here. There are going to be different thresholds that produce good looking images in different geographies and at different scales. The good news is that we are talking about visual artifacts that end up in rendered maps, not the underlying census data associated with the different geographies.

I wonder if the right approach is to create a new notebook that tackles this issue head on by showing some examples of what can happen if the threshold is too high and compares those to images when the threshold is more appropriate. There can be a few different examples to make it clear that there is no perfect answer. Then do the same things for when the threshold is too low. The idea of this is to help users learn that they may need some manual tweaking to get exactly what they want, and some guidance as to which direction to move when they don't get it.

Of course we'd like the defaults to produce good looking results in as many cases as possible, but the reason we have the optional arg is so people can tweak it.
