### ISSUE TITLE
Fall back on TIGER shapefiles when CB files are not available.

### ISSUE THREAD

**Issue by CanyonFoot** [vengroff/censusdis#163]
Following up on last week's issue, I've been thinking about the best way to improve geometry access for years/geographies where the CB files are not available on the TIGER site.

Since map.py already contains code to process the TIGER (i.e. non-CB) urls for any given year/geography, it's possible to just `try` `read_cb_shapefile`, and if an exception occurs, fall back on `read_shapefile`. I have tested a basic version of this and it works well for getting the 2011, 2012, and pre-2010 shapefiles. It might be good to print a message giving some transparency about what's being retrieved (e.g. 'Getting CB shapefiles ...', 'No CB shapefile available, trying full TIGER file...') Case-specific support would still be needed for the oldest files (2000 and 1990) since those are given their own CB directory.

As part of this change, it would be possible to add support for downloading block level geometries (not currently supported because they are not given a CB version) for decennial queries. These can get quite large so it might be worth throwing some kind of warning to that effect when a user requests the blocks. More generally, the TIGER files cover a much wide range of boundaries than what's available as a CB file so making this change could improve support for the less common geographies.

If you think this plan makes sense, I'll get working and post a PR in the next week or two.

**Comment by vengroff** [comment]
Looks good to me.

**Comment by vengroff** [comment]
I'd do either `logger.warning` or maybe better to do `logger.info` for the case where we fall back on tiger files. It's a tough call because info is so often filtered out and warning is a little more dramatic than this really is.
