### ISSUE TITLE
Support wide survey datasets.

### ISSUE THREAD

**Issue by vengroff** [vengroff/censusdis#93]
There are certain data sets that are survey based with weighted columns. Some, like `'cps/internet/nov'` in the 2021
vintage are really wide. This means that behind the scenes, `ced.download` has to load them in blocks of 50 or fewer
variables at a time and merge them together. See `ced._download_multiple` for the code that does this. If you read the 
internal comments, you will see that there are two possible strategies, the `merge` and the `concat` strategies. But there
are cases where neither one works. The problem, at least for the `'cps/internet/nov'`, but probably for others, is that the
keys used to merge are not unique.

So, 

```python
all_vars = ced.variables.all_variables('cps/internet/nov', 2021, None)

df = ced.download(
    'cps/internet/nov', 
    2021,
    download_variables = all_vars['VARIABLE'],
    
    state=WA
)
```

fails with

```
---------------------------------------------------------------------------
CensusApiException                        Traceback (most recent call last)
Cell In[74], line 1
----> 1 df = ced.download(
      2     'cps/internet/nov', 
      3     2021,
      4     download_variables = all_vars['VARIABLE'],
      5     
      6     state=WA
      7 )

File ~/Library/Caches/pypoetry/virtualenvs/censusdis-intro-zD9x84f5-py3.9/lib/python3.9/site-packages/censusdis/data.py:769, in download(dataset, vintage, download_variables, group, leaves_of_group, set_to_nan, skip_annotations, with_geometry, api_key, variable_cache, **kwargs)
    767 # Special case if we are trying to get too many fields.
    768 if len(download_variables) > _MAX_VARIABLES_PER_DOWNLOAD:
--> 769     return _download_multiple(
    770         dataset,
    771         vintage,
    772         download_variables,
    773         key=api_key,
    774         census_variables=variable_cache,
    775         with_geometry=with_geometry,
    776         **kwargs,
    777     )
    779 # Prefetch all the types before we load the data.
    780 # That way we fail fast if a field is not known.
    781 _prefetch_variable_types(dataset, vintage, download_variables, variable_cache)

File ~/Library/Caches/pypoetry/virtualenvs/censusdis-intro-zD9x84f5-py3.9/lib/python3.9/site-packages/censusdis/data.py:240, in _download_multiple(dataset, vintage, download_variables, key, census_variables, with_geometry, **kwargs)
    233 for df_slice in dfs[1:]:
    234     if not (
    235         rows0 == len(df_slice.index)
    236         and dfs[0][geo_key_variables].equals(df_slice[geo_key_variables])
    237     ):
    238         # At least one difference. So we cannot use the
    239         # concat strategy either.
--> 240         raise CensusApiException(
    241             "Neither the merge nor the concat strategy is viable. "
    242             "We made multiple queries to the census API because more than "
    243             f"{_MAX_VARIABLES_PER_DOWNLOAD} variables were requested. "
    244             "If you don't need all the variables, it is always safer to "
    245             f"download less than {_MAX_VARIABLES_PER_DOWNLOAD} variables. "
    246         )
    248 # Concat strategy is as safe as it will ever be. We hope the server
    249 # side did not reorder the results across queries.
    250 logger.info(
    251     "Using the concat strategy, which is not guaranteed reliable if "
    252     "the census API returned data for multiple sub-queries of less than "
   (...)
    257     _MAX_VARIABLES_PER_DOWNLOAD,
    258 )

CensusApiException: Neither the merge nor the concat strategy is viable. We made multiple queries to the census API because more than 50 variables were requested. If you don't need all the variables, it is always safer to download less than 50 variables. 
```

The solution, I believe, is to let the user specify a set of additional columns that are part of the unique key for each row, to
go along with the geography. In the `'cps/internet/nov'` dataset, these are `QSTNUM` and `OCCURNUM`. We could do this,
perhaps, by adding an optional `row_key=` argument of type `Union[str, Iterable[str]]` to `ced.download` to specify them.

As an alternative, it might be possible to discover them. For example,

```python
all_vars = ced.variables.all_variables('cps/internet/nov', 2021, None)

all_vars[all_vars['LABEL'].str.contains('Unique.*identifier')]
```

will find them.

If this looks like a reliable way of doing it, then we could just add an optional Boolean arg to `ced.download` to 
trigger this behavior.

So this issue requires both coming up with a good design using one of the options above, or something different, and then implementing the chosen approach.

**Comment by CanyonFoot** [comment]
I have a version of the suggested fix working, but I have an implementation question. Do you think that the `row_keys` merge should be treated as a separate strategy from the `geo_key_variables` based merge? If row keys are provided, the `geo_key_variables` still need to be included as join columns to prevent duplicating the geo columns (e.g., we want to avoid `STATE_X`, `STATE_Y`,... in the final dataframe). It's possible to just always add the `row_keys` (if they are supplied) to the join columns and leave the rest of the code unchanged with edits to the error messages. Does that make sense or would you rather treat the `row_keys` merge as it's own strategy and add it to `__dw_strategy_metrics`?

**Comment by vengroff** [comment]
I think it’s fine to do as you suggest and augment the existing geo_key_variables strategy. Sent from my iPhoneOn May 29, 2023, at 15:10, Canyon Foot ***@***.***> wrote:﻿
I have a version of the suggested fix working, but I have an implementation question. Do you think that the row_keys merge should be treated as a separate strategy from the geo_key_variables based merge? If row keys are provided, the geo_key_variables still need to be included as join columns to prevent duplicating the geo columns (e.g., we want to avoid STATE_X, STATE_Y,... in the final dataframe). It's possible to just always add the row_keys (if they are supplied) to the join columns and leave the rest of the code unchanged with edits to the error messages. Does that make sense or would you rather treat the row_keys merge as it's own strategy and add it to __dw_strategy_metrics?
