### ISSUE TITLE
Fix API docs so they work on readthedocs.io again

### ISSUE THREAD

**Issue by vengroff** [vengroff/censusdis#94]
If you look at the docs at https://censusdis.readthedocs.io/en/0.13.3/api.html you will see that there are
no docs for functions in the packages `censusdis.data` and `censusdis.maps`. There used to be in 
https://censusdis.readthedocs.io/en/0.10.6/api.html. This might have to do with moving some stuff
to `_impl`, but that is just a guess.

While you are doing this, a nice pass through the docs to make sure they read well and there are not things
missing would be awesome. If that feels like a bigger task, then feel free to open another issue for it.

**Comment by tarunsamanta2k20** [comment]
May I know how to run this project?

**Comment by vengroff** [comment]
Hi @tarunsamanta2k20,

The issue is the API docs are not generating properly. To see this, clone the repo, then go into the `doc` directory and run

```bash
make html
```

This should create a directory `_build/html` with an `index.html` in it. Open that file in your browser and on the left nav you should see something like this

<img width="290" alt="image" src="https://user-images.githubusercontent.com/6465299/235917721-8575e4d1-b985-4ecb-bab5-b9dd27e68824.png">

Click on "censusdis API Reference" and the body of the page should look like this

<img width="393" alt="image" src="https://user-images.githubusercontent.com/6465299/235917997-4ee94605-904e-402d-82df-dfc5bcfcbfb7.png">

The issue is that the `censusdis.data` and `censusdis.maps` packages have no documentation even though they contain several public functions. This worked properly in 0.10.3 as can be seen at https://censusdis.readthedocs.io/en/0.10.3/api.html. But in the latest version, it the docs for the contents of those two packages do not appear, just as they do not appear when you build them locally as I did above.

**Comment by vengroff** [comment]
If your question on how to "run the project" is more general, see https://github.com/vengroff/censusdis-tutorial and follow the links in the readme to live tutorial notebooks on mybinder.org.

**Comment by CanyonFoot** [comment]
The docs were not being generated correctly due to an issue with importing `rasterio` (itself imported by `contextily` in `maps.py`) while `numpy` is mocked. The easiest solution is to remove `numpy` from the list of mocked packages. I'll create a PR after I go through the documentation for readability.

**Comment by vengroff** [comment]
@CanyonFoot Looking forward to your contribution.

**Comment by vengroff** [comment]
Merged. Thanks, @CanyonFoot
